/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvolutionMetric;

/**
 *
 * @author aryan_000
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        
        String str = "<html> <ul> ";
        str += "<li> BOC  : Birth of a Class </li> <br>";
        str += "<li> LOC  : Line of Codes  of a Class </li> <br>";
        str += "<li> TACH  : Total amount of changes in a Class </li> <br>";
        str += "<li> CHO :  Change Occurred in a Class  </li><br>";
        str += "<li> CHD :  Change Density </li><br>";
        str += "<li> FCH  : First Time Change Introduced to a Class </li><br>";
        str += "<li> LCH  : Last TIme Change Introduced to a Class </li><br>";
        str += "<li> FRCH  : Frequency of changes of a Class </li><br>";
        str += "<li> CSB  : Changes Since Birth in a Class </li><br>";
        str += "<li> CSBS  : Changes Since Birth Normalised by Size of a Class </li><br>";
        str += "<li> LCA  : Last Change Amount in a Class </li><br>";
        str += "<li> LCD  : Last Change Density of a Class </li><br>";
        str += "<li> WCH  : Weighted Changes of a Class </li><br>";
        str += "<li> WCD  : Weighted Changes Density  of a Class </li><br>";
        str += "<li> ACDF  : Aggregated change Density normalised by frequence of changes in a class </li><br>";
        str += "<li> ATAF :  Aggregated change Size normalised by frequency of change in a class </li><br>";
        str += "<li> WFR : Weighted Frequency of changes </li><br>";
        str += "<li> ICP  : Internal CHange Probability of a class </li><br>";
        str += "<li> CP  : Change Pronennes of a class  </li><br>";
        
        str += "</ol> </html>";
        
        metrics_area.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        metrics_scrollpane = new javax.swing.JScrollPane();
        metrics_area = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        heading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(204, 51, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Evolution Metrics ");

        metrics_area.setText(" ");
        metrics_scrollpane.setViewportView(metrics_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(metrics_scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metrics_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heading;
    private javax.swing.JLabel metrics_area;
    private javax.swing.JScrollPane metrics_scrollpane;
    // End of variables declaration//GEN-END:variables
}
