/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvolutionMetric;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aryan_000
 */
public class CompleteReport extends javax.swing.JFrame {

    /**
     * Creates new form Complete
     */
    public CompleteReport() {
        initComponents();
         this.setResizable(false);
         
    }

    public CompleteReport(File f1 , File f2) {
        initComponents();
        accuracy_file_bar.setText(f1.getAbsolutePath());
        attribute_file_bar.setText(f2.getAbsolutePath());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accuracy_label = new javax.swing.JLabel();
        accuracy_file_bar = new javax.swing.JLabel();
        attribute_file_bar = new javax.swing.JLabel();
        attribute_selection_label = new javax.swing.JLabel();
        accuracy_folder_open = new javax.swing.JButton();
        close_button1 = new javax.swing.JButton();
        open_accuracy = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        open_attribute_file = new javax.swing.JButton();
        open_attribute_folder = new javax.swing.JButton();
        close_button2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metric Calculation Complete");
        setForeground(new java.awt.Color(102, 255, 204));

        accuracy_label.setText("Accuracy is Saved as : ");

        accuracy_file_bar.setText(" ");
        accuracy_file_bar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        attribute_file_bar.setText(" ");
        attribute_file_bar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        attribute_selection_label.setText("Attribute Selection is Saved as : ");

        accuracy_folder_open.setText("Open Containing Folder");
        accuracy_folder_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accuracy_folder_openActionPerformed(evt);
            }
        });

        close_button1.setText("Close");
        close_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_button1ActionPerformed(evt);
            }
        });

        open_accuracy.setText("Open");
        open_accuracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_accuracyActionPerformed(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/todo_good.jpg"))); // NOI18N
        icon.setText("jLabel5");

        heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(51, 51, 255));
        heading.setText("Report Generated");

        open_attribute_file.setText("Open");
        open_attribute_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_attribute_fileActionPerformed(evt);
            }
        });

        open_attribute_folder.setText("Open Containing Folder");
        open_attribute_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_attribute_folderActionPerformed(evt);
            }
        });

        close_button2.setText("Close");
        close_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(attribute_selection_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attribute_file_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(open_accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(accuracy_label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accuracy_folder_open, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(close_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(accuracy_file_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(open_attribute_file, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(open_attribute_folder, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(close_button2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heading))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accuracy_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accuracy_file_bar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(open_accuracy)
                    .addComponent(accuracy_folder_open)
                    .addComponent(close_button1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attribute_selection_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribute_file_bar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(open_attribute_file)
                    .addComponent(open_attribute_folder)
                    .addComponent(close_button2))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_button1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_close_button1ActionPerformed

   
    private void open_accuracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_accuracyActionPerformed
        // TODO add your handling code here:
        
        String location = accuracy_file_bar.getText();
         File file = new File(location);
//         location = "C:\\Users\\aryan_000\\Desktop\\output.xls";
        try {
            this.dispose();
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(CompleteReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_open_accuracyActionPerformed

    private void accuracy_folder_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accuracy_folder_openActionPerformed
        // TODO add your handling code here:
        String location = accuracy_file_bar.getText();
         File file = new File(new File(location).getParent());
//         location = "C:\\Users\\aryan_000\\Desktop\\output.xls";
        try {
            this.dispose();
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(CompleteReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_accuracy_folder_openActionPerformed

    private void open_attribute_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_attribute_fileActionPerformed
        // TODO add your handling code here:
        
        String location = attribute_file_bar.getText();
         File file = new File(location);
//         location = "C:\\Users\\aryan_000\\Desktop\\output.xls";
        try {
            this.dispose();
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(CompleteReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_open_attribute_fileActionPerformed

    private void open_attribute_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_attribute_folderActionPerformed
        // TODO add your handling code here:
        String location = accuracy_file_bar.getText();
         File file = new File(new File(location).getParent());
//         location = "C:\\Users\\aryan_000\\Desktop\\output.xls";
        try {
            this.dispose();
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(CompleteReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_open_attribute_folderActionPerformed

    private void close_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_button2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_close_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompleteReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompleteReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accuracy_file_bar;
    private javax.swing.JButton accuracy_folder_open;
    private javax.swing.JLabel accuracy_label;
    private javax.swing.JLabel attribute_file_bar;
    private javax.swing.JLabel attribute_selection_label;
    private javax.swing.JButton close_button1;
    private javax.swing.JButton close_button2;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel icon;
    private javax.swing.JButton open_accuracy;
    private javax.swing.JButton open_attribute_file;
    private javax.swing.JButton open_attribute_folder;
    // End of variables declaration//GEN-END:variables
}
